name: Test

on:
    push:
    pull_request:
    schedule: 
      - cron: '* 12 * * *'


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - uses: denolib/setup-deno@master
            with:
              deno-version: 1.1.0
          - name: Build
            run: deno test --allow-read
