name: Test

on:
    [push, pull_request]                


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - uses: denolib/setup-deno@master
            with:
              deno-version: 0.36
          - name: Build
            run: deno test